# Generated by Django 5.0.7 on 2024-08-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0002_customuser_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="remove",
            field=models.BooleanField(default=False),
        ),
    ]
