# Generated by Django 5.0.7 on 2024-08-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0003_post_remove"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="urlImage",
            field=models.URLField(blank=True, null=True),
        ),
    ]
