# Generated by Django 5.0.7 on 2024-08-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0004_post_urlimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
