# Generated by Django 5.0.7 on 2024-08-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0005_comment_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="web_app.tag"
            ),
        ),
    ]
